<?php
// $Id$


function import_system($field) {
  $system["description"] = t("The import module is a central place where all imported content comes together.");
  return $system[$field];
}


function import_perm() {
  return array("access import");
}

function import_link($type, $node = 0, $main = 0) {
  if ($type == "import") {
    $links[] = l(t("latest news"), "import/", array("title" => t("Read the latest imported news.")));
    $links[] = l(t("news sources"), "import/sources", array("title" => t("View a list of all the websites we import news from.")));
    if (module_exist("taxonomy_dhtml")) {
      $links[] = l(t("news by category"), "import/categories/item", array("title" => t("View a list of news items organized by category.")));
      $links[] = l(t("news sources by category"), "import/categories/feed", array("title" => t("View a list of feeds organized by category.")));
    }
  }

  if (($type == "page") && (user_access("access import"))) {
    $links[] = l(t("import"), "import/", array("title" => t("Read the latest imported news.")));
  }

  return $links ? $links : array();
}

function import_theme_latestitem($node) {


  theme("node", $node, 0);
}

function import_page_latest() {


  theme("header");

  import_menu();

  $nids = module_invoke_all("import", "items");
  $result = pager_query("SELECT nid FROM node WHERE nid IN (". implode(",", $nids) .") ORDER BY created DESC, nid DESC", ($user->nodes ? $user->nodes : variable_get("default_nodes_main", 10)), 0); 

  while ($import_node = db_fetch_object($result)) {
    theme("import_theme_latestitem", node_load(array("nid" => $import_node->nid)));
  }

  print pager_display("", ($user->nodes ? $user->nodes : variable_get("default_nodes_main", 10)), 0);

  theme("footer");

}

function import_categories($type) {


  $boxes = taxonomy_dhtml_overview($type);
  theme("header");
  import_menu();
  for ($n=0; $n < count($boxes); $n++) {
    theme("box", $boxes[$n]["subject"], $boxes[$n]["content"]);
  }
  theme("footer");

}

function import_theme_source($node) {


  theme("node", $node, 1);
}

function import_page_sources() {


  theme("header");

  import_menu();

  $nids = module_invoke_all("import", "sources");
  $result = pager_query("SELECT nid FROM node WHERE nid IN (". implode(",", $nids) .") ORDER BY title, nid", ($user->nodes ? $user->nodes : variable_get("default_nodes_main", 10)), 0);

  while ($import_source = db_fetch_object($result)) {
    theme("import_theme_source", node_load(array("nid" => $import_source->nid)));
  }

  print pager_display("", ($user->nodes ? $user->nodes : variable_get("default_nodes_main", 10)), 0);

  theme("footer");
}

function import_menu() {
  $links = module_invoke_all("link", "import");
  theme("import_theme_menu", $links);
}

function import_theme_menu($links) {


  theme("box", t("News feeds"), "<div align=\"center\">". theme("links", $links) ."</div>");
}

function import_page() {


  $op = arg(1);

  switch ($op) {
    case "sources":
      import_page_sources();
      break;
    case "categories":
      $type = arg(2);
      import_categories($type);  
      break;  
    default:
      import_page_latest();
  }
}
?>