<?php
// $Id$

/**
 * @file
 * An example use case for the import API written to import users from an
 * existing Drupal installation.
 *
 * In order for this to work you will likely need to setup a second datasource
 * in settings.php to perform the selects from.
 */

/**
 * hook_import_stage()
 *
 */
function import_user_import_stage() {
  if(variable_get('import_user_staged',FALSE) == FALSE) {

    // select all of the old uids we will be importing.  Use the datasource
    // we are importing from

    db_set_active('old');
    $sql = "SELECT uid from users";
    $result = db_query($sql);
    db_set_active('default');

    while ($user = db_fetch_object($result)) {

      // create an array containing identifier and type both of which are used in
      // this modules process hook

      $attr = array();
      $attr['impid'] = $user->uid;
      $attr['type'] = 'user';

      // pass the array to the import_stage method

      import_stage($attr);
    }
    // set this variable to true to eliminate restaging the data

    variable_set('import_user_staged',TRUE);
  }
}

function import_user_import_process($data) {
  drupal_set_message("import_user_import_process");
  if($data->type == 'user') {
    db_set_active('old');
    // get the old users data
    db_set_active('old');
    $sql = "SELECT uid, name, pass, mail, mode, sort, threshold, theme, ".
           "signature, created, access, login, status, timezone, language, ".
           "picture, init, data from users where uid = %d";
    $sql_insert = "INSERT into users(name, pass, mail, mode, sort, threshold, ".
      "theme, signature, created, access, login, status, timezone, language, ".
      "picture, init, data) values('%s','%s','%s',%d, %d, %d, '%s', '%s', %d, ".
      "%d, %d, %d, '%s', '%s', '%s', '%s', '%s')";
    $user = db_fetch_object(db_query($sql,$data->impid));
    db_set_active('defualt');
    $status = FALSE;
    if($user->uid > 0) {
      $status = db_query($sql_insert,$user->name, $user->pass, $user->mail,
        $user->mode, $user->sort, $user->threshold, $user->theme,
        $user->signature, $user->created, $user->access, $user->login,
        $user->status, $user->timezone, $user->language, $user->picture,
        $user->init, $user->data);
    }
    if($status == FALSE) {
      import_fail($data,'User Import failed'.print_r($user,true));
    } else {
      import_pass($data,'User Import failed'.print_r($user,true));
    }
  }
}