<?php
// $Id$

/**
 * Implementation of hook_install().
 *
 * Remove the variables, nodes and schema corresponding to the module.
 */
function import_user_install() {
  define('IMPORT_USER_STAGED', FALSE);
}
/**
 * Implementation of hook_uninstall().
 *
 * Remove the variables, nodes and schema corresponding to the module.
 */
function import_user_uninstall() {
  variable_del('import_user_staged');
}
